apiVersion: v1
kind: Service
metadata:
  name: heart-disease-api
  labels:
    app: heart-disease-api
spec:
  type: LoadBalancer
  selector:
    app: heart-disease-api
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080  # For minikube access
  sessionAffinity: ClientIP

